### ISSUE TITLE
OpenGauss when update-database

### ISSUE THREAD

**Issue by sdjnzjz** [dotnetcore/EntityFrameworkCore.GaussDB#4]
GaussDB.GaussDBException (0x80004005): Received backend message AuthenticationRequest while expecting AuthenticationRequestMessage. Please file a bug.
   at GaussDB.Util.Statics.ThrowIfMsgWrongType[T](IBackendMessage msg, GaussDBConnector connector)
   at GaussDB.Util.Statics.Expect[T](IBackendMessage msg, GaussDBConnector connector)
   at GaussDB.Internal.GaussDBConnector.GaussDBAuthenticateSASLSha256(String salt, String token, Int32 iteration, String username, Boolean async, CancellationToken cancellationToken)
   at GaussDB.Internal.GaussDBConnector.Authenticate(String username, GaussDBTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at GaussDB.Internal.GaussDBConnector.<Open>g__OpenCore|216_1(GaussDBConnector conn, SslMode sslMode, GaussDBTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at GaussDB.Internal.GaussDBConnector.Open(GaussDBTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at GaussDB.UnpooledDataSource.Get(GaussDBConnection conn, GaussDBTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at GaussDB.GaussDBConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at GaussDB.GaussDBConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at GaussDB.EntityFrameworkCore.PostgreSQL.Storage.Internal.GaussDBDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at GaussDB.EntityFrameworkCore.PostgreSQL.Storage.Internal.GaussDBDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at GaussDB.EntityFrameworkCore.PostgreSQL.Storage.Internal.GaussDBDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at GaussDB.EntityFrameworkCore.PostgreSQL.Migrations.Internal.GaussDBMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Received backend message AuthenticationRequest while expecting AuthenticationRequestMessage. Please file a bug.

**Comment by wangpengxpy** [comment]
未提供进一步信息，此问题暂时关闭
